// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompletePlantController from "./autocomplete_plant_controller"
application.register("autocomplete-plant", AutocompletePlantController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)
